140
driver_CanSafelyOvertake_vehicle
driver_Overtake_vehicle

141
vehicle_CanBeSafelyOvertakenIn_markedLane
IsSafeToOvertakeToTheLeftOf_vehicle
driver_OvertakeToTheLeftOf_vehicle

142
driver_OvertakeToTheRightOf_vehicle

143-left
IsSafeToPassIn_MarkedLane
IsSafeToOvertakeIn_MarkedLane
IsSafeToPassToTheLeftOf_vehicle
IsOtherwiseSafeToPassToTheLeftOf_vehicle
IsSafeToOvertakeToTheLeftOf_vehicle
driver_DrivePastToTheLeftOf_vehicle
driver_OvertakeToTheLeftOf_vehicle
IsOtherwiseSafeToOvertakeToTheLeftOf_vehicle


143-right
IsSafeToPassIn_markedLane
IsSafeToOvertakeIn_MarkedLane
IsSafeToPassToTheRightOf_vehicle
driver_DrivePastToTheRightOf_vehicle
driver_OvertakeToTheRightOf_vehicle

144
driver_IsOvertaking_vehicle
driver_PassAtSufficientDistanceToAvoidCollisionWith_vehicle
driver_PassAtSufficientDistanceToAvoidObstructingThePathOf_vehicle
driver_IsAtSufficientDistancePastToAvoidCollisionWith_vehicle
driver_IsAtSufficientDistancePastToAvoidObstructingThePathOf_vehicle


145
driver_IsOvertakingByCrossingADividingLine_anotherDriver
driver_IsOvertakingByCrossingToTheRightOfTheCentreOfTheRoad_anotherDriver
driver_IsAtASufficientDistanceToAvoidACollisionInFrontOf_anotherDriver
driver_HasPassed_anotherDriver
anotherDriver_IncreaseTheSpeed